.TH nwtsmerge 1 2003/08/30 libnw-1.30.02
.SH "NAME"
nwtsmerge \- merge 2 NWN SET resources
.SH "SYNOPSIS"
nwtsmerge -1 ts1.set -2 ts2.set
.SH "DESCRIPTION"
nwtsmerge is the beginnings of an automatic tileset merger.
.P
It is an error to omit either the -1 flag or the -2 flag.
.SH "EXIT STATUS"
On success, 0 is returned.
For any fatal error, a non-zero value is returned.
.SH "BUGS"
nwtsmerge is not complete, though it is a start.
.SH "AUTHOR"
Marty Shannon <mailto:mshannon@domovina.org>
.SH "SEE ALSO"
nwaggext(1),
nwresext(1),
itpdis(1).
